name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v3
        with:
          manifests: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: flask-deployment
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: flask-app
              template:
                metadata:
                  labels:
                    app: flask-app
                spec:
                  containers:
                    - name: flask
                      image: flask-ci-cd-demo
                      ports:
                        - containerPort: 5000